W-17040933-Add-AsyncAPI-notes-to-ACB-docs-CP
mulesoft/docs-code-builder pull request #396
Opened 2024-10-22 21:19 UTC by Crispy-Salesforce

W-17040933-Add-AsyncAPI-notes-to-ACB-docs-CP

2024-10-22 22:02 UTC, simoneegeib commented on modules/ROOT/pages/imp-asyncapi.adoc
> +If a *Message Listener* receives an invalid message, it’s sent to the dead-letter queue (you must set up one dead-letter queue).
Is this really correct?

2024-10-22 22:03 UTC, simoneegeib commented on modules/ROOT/pages/imp-asyncapi.adoc
> -The scaffolder transforms each `publish` operation into a *Message Listener* operation.
I think we should add the same sentence for 'subscribe' operations. Also, can we link to the AsyncAPI spec to explain why publish is subscribe and vice versa?

2024-10-22 22:04 UTC, simoneegeib commented on modules/ROOT/pages/imp-asyncapi.adoc
> +When re-scaffolding, the scaffolder acts on new combinations of channel, server, and *publish* operation groupings in the specification and does not re-scaffold combinations that are not new.
Not only publish. Even though we're not adding a new flow for subscribe operations, we still update the APIkit module in teh project

2024-10-23 16:55 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +If a *Message Listener* receives an invalid message, it’s sent to the dead-letter queue (you must set up one dead-letter queue).
It was taken from the enhanced doc, but according to Aby, it’s untrue. Removed.

2024-10-23 17:22 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> -The scaffolder transforms each `publish` operation into a *Message Listener* operation.
OK! Thanks!

2024-10-23 17:25 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +When re-scaffolding, the scaffolder acts on new combinations of channel, server, and *publish* operation groupings in the specification and does not re-scaffold combinations that are not new.
OK! Thanks!

2024-10-24 07:34 UTC, aby-philip-sf commented on modules/ROOT/pages/imp-asyncapi.adoc
> +** *Subscribe* (`<apikit-asyncapi:publish/>`): AsyncAPI *subscribe* operations in the specification are available for configuration as AsyncAPI *Subscribe* operations. See the <<ex-flows-implemented,
AsyncAPI *subscribe* operations in the specification are available for configuration as AsyncAPI *Publish* operations.

2024-10-24 07:39 UTC, aby-philip-sf requested changes

2024-10-24 07:39 UTC, aby-philip-sf commented on modules/ROOT/pages/imp-asyncapi.adoc
> +** *Message Listener* (`<apikit-asyncapi:message-listener/>`): AsyncAPI *publish* operations in the specification are configurable *Message Listener* operations. The system publishes messages to a ch
`are configurable` to be changed to `are configurable as`

2024-10-24 07:39 UTC, aby-philip-sf commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The scaffolder transforms each *publish* and *subscribe* operation into a *Message Listener* operation allowing the Mule application to read from the specified channel and process the published messa
omit the `and *subscribe*`
Only the publish operations are trasformed as Message Listener in the mule application

2024-10-24 13:34 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +** *Subscribe* (`<apikit-asyncapi:publish/>`): AsyncAPI *subscribe* operations in the specification are available for configuration as AsyncAPI *Subscribe* operations. See the <<ex-flows-implemented,
OK! Thanks!

2024-10-24 13:35 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +** *Message Listener* (`<apikit-asyncapi:message-listener/>`): AsyncAPI *publish* operations in the specification are configurable *Message Listener* operations. The system publishes messages to a ch
OK! Thanks!

2024-10-24 13:36 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The scaffolder transforms each *publish* and *subscribe* operation into a *Message Listener* operation allowing the Mule application to read from the specified channel and process the published messa
OK! Thanks!

2024-10-24 13:44 UTC, aby-philip-sf submitted a review, later dismissed
LGTM

2024-10-24 19:02 UTC, sathya0 submitted a review, later dismissed

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +* Creates a new Mule project with a separate flow for each *publish* operation in the specification
```suggestion
* Creates a new Mule project with a separate flow for each *Publish* operation in the specification
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +* Generates an empty XML file with the name of your Mule project if the AsyncAPI spec doesn’t include a *publish* operation
```suggestion
* Generates an empty XML file with the name of your Mule project if the AsyncAPI spec doesn’t include a *Publish* operation
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +** *Message Listener* (`<apikit-asyncapi:message-listener/>`): AsyncAPI *publish* operations in the specification are configurable as *Message Listener* operations. The system publishes messages to a
```suggestion
** *Message Listener* (`<apikit-asyncapi:message-listener/>`): AsyncAPI *Publish* operations in the specification are configurable as *Message Listener* operations. The system publishes messages to a channel, and the Mule application listens for these messages. See examples in <<ex-flows-scaffolded>>.
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The scaffolder transforms each *publish* operation into a *Message Listener* operation allowing the Mule application to read from the specified channel and process the published messages.
```suggestion
The scaffolder transforms each *Publish* operation into a *Message Listener* operation allowing the Mule application to read from the specified channel and process the published messages.
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +When re-scaffolding, the scaffolder acts on new combinations of channel, server, and *publish* and *subscribe* operations groupings in the specification and doesn’t re-scaffold combinations that aren
```suggestion
When re-scaffolding, the scaffolder acts on new combinations of channel, server, and *Publish* and *Subscribe* operations groupings in the specification and doesn’t re-scaffold combinations that aren’t new.
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The scaffolder generates a `flow.xml` file with a flow for each *publish* operation in the AsyncAPI specification (for re-scaffolding behavior, see <<scaffold-procedures>>). The example describes the
```suggestion
The scaffolder generates a `flow.xml` file with a flow for each *Publish* operation in the AsyncAPI specification (for re-scaffolding behavior, see <<scaffold-procedures>>). The example describes the generated flows and configures components that provide order-processing logic to some of the flows. 
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The following example defines an API specification that uses Anypoint MQ and Kafka protocols. The specification defines https://www.asyncapi.com/docs/concepts/channel[channels] for orders (new, confi
```suggestion
The following example defines an API specification that uses Anypoint MQ and Kafka protocols. The specification defines https://www.asyncapi.com/docs/concepts/channel[channels] for orders (new, confirmed, and cancelled orders) that use Anypoint MQ, and it defines a channel that uses Kafka for backorders (items that are not in stock). Each channel includes a *Publish* and *Subscribe* operation. The https://www.asyncapi.com/docs/concepts/server[server] settings in the specification define message brokers that determine the connectors to use (_indirectly_) when publishing events or subscribing to events through operations in the AsyncAPI module.
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +When scaffolding the specification into an implementation project, Anypoint Code Builder creates a flow (`<flow/>`) for each *publish* operation and transforms the *publish* operation into a *Message
```suggestion
When scaffolding the specification into an implementation project, Anypoint Code Builder creates a flow (`<flow/>`) for each *Publish* operation and transforms the *Publish* operation into a *Message Listener* source from the AsyncAPI module for APIkit (`<apikit-asyncapi:message-listener/>`). Each flow also includes a *Logger* component. For more information about the module, see xref:apikit::apikit-asyncapi-module-reference.adoc[].
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +. Posts the Slack confirmation message by using the *<slack:post-message/>*`* operation from the Slack connector
```suggestion
. Posts the Slack confirmation message by using the *<slack:post-message/>*`* operation from Slack Connector 
```

2024-10-24 19:02 UTC, sathya0 commented on modules/ROOT/pages/imp-asyncapi.adoc
> +. Emails the confirmation message by using the *<email:send/>* operation from the Email connector
```suggestion
. Emails the confirmation message by using the *<email:send/>* operation from Email Connector
```

2024-10-24 19:06 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +* Creates a new Mule project with a separate flow for each *publish* operation in the specification
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:07 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +* Generates an empty XML file with the name of your Mule project if the AsyncAPI spec doesn’t include a *publish* operation
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:07 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +** *Message Listener* (`<apikit-asyncapi:message-listener/>`): AsyncAPI *publish* operations in the specification are configurable as *Message Listener* operations. The system publishes messages to a
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:07 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The scaffolder transforms each *publish* operation into a *Message Listener* operation allowing the Mule application to read from the specified channel and process the published messages.
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:07 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +When re-scaffolding, the scaffolder acts on new combinations of channel, server, and *publish* and *subscribe* operations groupings in the specification and doesn’t re-scaffold combinations that aren
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:07 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The scaffolder generates a `flow.xml` file with a flow for each *publish* operation in the AsyncAPI specification (for re-scaffolding behavior, see <<scaffold-procedures>>). The example describes the
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:08 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +The following example defines an API specification that uses Anypoint MQ and Kafka protocols. The specification defines https://www.asyncapi.com/docs/concepts/channel[channels] for orders (new, confi
In the AsyncAPI docs, `publish` and `subscribe` operations are not capitalized. Thanks!

2024-10-24 19:08 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +When scaffolding the specification into an implementation project, Anypoint Code Builder creates a flow (`<flow/>`) for each *publish* operation and transforms the *publish* operation into a *Message
Great catch! Thanks!

2024-10-24 19:11 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +. Posts the Slack confirmation message by using the *<slack:post-message/>*`* operation from the Slack connector
OK! Thanks!

2024-10-24 19:12 UTC, Crispy-Salesforce commented on modules/ROOT/pages/imp-asyncapi.adoc
> +. Emails the confirmation message by using the *<email:send/>* operation from the Email connector
OK! Thanks!

2024-10-24 19:15 UTC, sathya0 approved these changes

2024-10-24 19:43 UTC, merged